/**
 * 영상·3D 제작 용어집 (영어 → 한국어).
 * 일반 번역기가 틀리기 쉬운 현장 용어(dolly → "인형"이 아니라 "달리")를 먼저 잡아 주고,
 * 자주 쓰는 프롬프트 단어는 API 없이도 바로 뜻을 보여 줘요. 클라이언트·서버 공용.
 *
 * 형식: [영어("대표형|별칭|별칭"), 한국어("주 의미, 비슷한 말"), 설명?]
 */
type Raw = [en: string, ko: string, note?: string];

export type GlossaryCategory =
  | "shot"
  | "camera"
  | "lens"
  | "light"
  | "color"
  | "film"
  | "composition"
  | "cg"
  | "style"
  | "mood"
  | "scene"
  | "motion"
  | "edit"
  | "audio"
  | "prompt"
  | "common";

export const GLOSSARY_CATEGORY_LABEL: Record<GlossaryCategory, string> = {
  shot: "샷",
  camera: "카메라 무빙",
  lens: "렌즈",
  light: "조명",
  color: "색·톤",
  film: "필름·화질",
  composition: "구도",
  cg: "3D·CG",
  style: "스타일",
  mood: "분위기",
  scene: "환경·날씨",
  motion: "움직임",
  edit: "편집",
  audio: "소리",
  prompt: "프롬프트",
  common: "일반",
};

const GROUPS: [GlossaryCategory, Raw[]][] = [
  [
    "shot",
    [
      ["extreme close-up|ecu|xcu|extreme closeup", "익스트림 클로즈업", "눈·입처럼 아주 작은 부분만 화면 가득"],
      ["close-up|closeup|cu", "클로즈업", "얼굴이나 사물을 화면 가득"],
      ["medium close-up|mcu", "미디엄 클로즈업", "가슴 위"],
      ["medium shot|mid shot|ms", "미디엄 샷", "허리 위"],
      ["cowboy shot|american shot", "카우보이 샷", "허벅지 위"],
      ["full shot|full body shot|full-length shot", "풀 샷, 전신 샷", "머리부터 발끝까지"],
      ["wide shot|ws", "와이드 샷", "인물과 주변 공간을 넓게"],
      ["long shot|ls", "롱 샷", "멀리서 넓게"],
      ["extreme wide shot|extreme long shot|ews|els", "익스트림 와이드 샷", "풍경 속 인물이 아주 작게"],
      ["establishing shot", "설정 샷", "장소·상황을 알려 주는 첫 샷"],
      ["insert shot|insert", "인서트 샷", "손·소품 등 디테일을 끼워 넣는 샷"],
      ["detail shot", "디테일 샷"],
      ["two shot", "투 샷", "두 사람을 한 화면에"],
      ["over-the-shoulder shot|over the shoulder|ots", "오버 더 숄더 샷", "어깨 너머로 상대를 봄"],
      ["point of view|pov|pov shot|first-person view", "시점 샷(POV)", "인물의 눈으로 보는 화면"],
      ["bird's-eye view|birds eye view|bird's eye view", "버즈아이 뷰, 수직 부감", "바로 위에서 내려다봄"],
      ["top-down view|top-down shot|top down|overhead shot|flat lay", "탑다운 샷", "정수리 위에서 수직으로"],
      ["high angle|high-angle shot", "하이 앵글, 부감", "위에서 내려다봄"],
      ["low angle|low-angle shot", "로우 앵글, 앙각", "아래에서 올려다봄"],
      ["eye level|eye-level shot", "아이 레벨", "눈높이"],
      ["dutch angle|dutch tilt|canted angle", "더치 앵글", "화면을 비스듬히 기울임(불안감)"],
      ["worm's-eye view|worms eye view", "웜즈아이 뷰", "바닥에서 극단적으로 올려다봄"],
      ["aerial shot|aerial view", "항공 샷, 에어리얼", "하늘에서 내려다봄"],
      ["drone shot", "드론 샷"],
      ["profile shot|side profile", "옆모습, 프로필 샷"],
      ["three-quarter view|3/4 view", "3/4 측면"],
      ["front view|frontal view", "정면"],
      ["back view|rear view", "뒷모습"],
      ["macro shot|macro", "매크로 샷, 접사"],
      ["reaction shot", "리액션 샷", "반응을 보여 주는 샷"],
      ["cutaway", "컷어웨이", "잠깐 다른 장면을 보여 주는 샷"],
      ["single shot", "원 샷", "한 사람만"],
      ["group shot", "그룹 샷"],
      ["headshot", "헤드샷, 증명사진 구도"],
      ["hero shot", "히어로 샷", "대상을 멋지게 강조하는 샷"],
    ],
  ],
  [
    "camera",
    [
      ["pan|panning|pan left|pan right", "팬", "카메라를 제자리에서 좌우로 회전"],
      ["tilt|tilt up|tilt down", "틸트", "카메라를 제자리에서 위아래로 회전"],
      ["dolly|dolly shot", "달리", "레일·바퀴로 카메라 자체가 이동"],
      ["dolly in|dolly-in", "달리 인", "카메라가 앞으로 다가감"],
      ["dolly out|dolly-out", "달리 아웃", "카메라가 뒤로 물러남"],
      ["push in|push-in|slow push in", "푸시 인", "천천히 다가가며 긴장감"],
      ["pull out|pull back|pull-back", "풀 아웃", "뒤로 빠지며 전체를 드러냄"],
      ["truck|trucking shot|truck left|truck right", "트럭", "카메라가 좌우로 평행 이동"],
      ["tracking shot|tracking|track", "트래킹 샷", "움직이는 대상을 따라감"],
      ["follow shot|following shot", "팔로우 샷", "인물 뒤를 따라감"],
      ["crane shot|crane up|crane down", "크레인 샷", "크레인으로 높이를 크게 바꿈"],
      ["jib|jib shot", "지브, 지미집"],
      ["pedestal|pedestal up|pedestal down", "페데스탈", "카메라 높이만 수직 이동"],
      ["zoom in", "줌 인", "렌즈로 확대(카메라는 제자리)"],
      ["zoom out", "줌 아웃", "렌즈로 축소"],
      ["crash zoom|snap zoom", "크래시 줌", "아주 빠른 줌"],
      ["dolly zoom|vertigo effect|contra-zoom|zolly", "달리 줌, 현기증 효과", "다가가며 줌을 빼서 배경 원근만 변함"],
      ["whip pan|swish pan", "휩 팬", "휙 돌아가는 아주 빠른 팬"],
      ["orbit|orbit shot|orbiting|circles around", "오빗", "대상 주위를 원을 그리며 돎"],
      ["arc shot|arc", "아크 샷", "대상 주위를 반원으로 이동"],
      ["360-degree shot|360 shot|360 degree rotation", "360도 회전 샷"],
      ["handheld|handheld camera|hand-held", "핸드헬드", "손으로 들고 찍어 자연스럽게 흔들림"],
      ["steadicam|steadicam shot", "스테디캠", "흔들림 없이 부드럽게 걸으며 촬영"],
      ["gimbal|gimbal shot", "짐벌", "전자식 흔들림 보정 장비"],
      ["fpv|fpv drone|fpv drone shot", "FPV 드론", "빠르고 역동적인 1인칭 드론 비행"],
      ["rack focus|focus pull|pull focus", "랙 포커스", "초점을 앞뒤 대상으로 옮김"],
      ["slow motion|slow-mo|slowmo", "슬로 모션"],
      ["time-lapse|timelapse", "타임랩스", "긴 시간을 빠르게 압축"],
      ["hyperlapse", "하이퍼랩스", "이동하며 찍는 타임랩스"],
      ["freeze frame", "프리즈 프레임", "화면 정지"],
      ["bullet time", "불릿 타임", "시간이 멈춘 듯 주위를 도는 효과"],
      ["reverse motion|reverse playback", "역재생"],
      ["camera shake|shaky cam", "카메라 흔들림"],
      ["locked-off shot|static shot|locked off|static camera", "고정 샷", "카메라가 움직이지 않음"],
      ["long take|oner|one-take|single take", "롱테이크, 원테이크", "끊지 않고 길게 한 번에"],
      ["camera movement|camera motion", "카메라 무빙"],
      ["camera follows", "카메라가 따라감"],
      ["camera rises|rising shot", "카메라가 올라감"],
      ["camera descends", "카메라가 내려옴"],
      ["smooth camera", "부드러운 카메라 움직임"],
      ["motion control", "모션 컨트롤", "같은 움직임을 정확히 반복하는 로봇 카메라"],
    ],
  ],
  [
    "lens",
    [
      ["wide-angle lens|wide angle lens|wide-angle|wide angle", "광각 렌즈", "넓게, 원근이 과장됨"],
      ["ultra-wide|ultra wide angle", "초광각"],
      ["telephoto lens|telephoto|long lens", "망원 렌즈", "멀리 있는 것을 당기고 배경을 압축"],
      ["fisheye lens|fisheye|fish-eye", "어안 렌즈", "둥글게 휘어진 극단적 광각"],
      ["macro lens", "매크로 렌즈", "접사용"],
      ["anamorphic lens|anamorphic", "아나모픽 렌즈", "가로로 긴 화면과 가로 플레어가 특징"],
      ["spherical lens", "구면 렌즈"],
      ["prime lens", "단렌즈"],
      ["zoom lens", "줌 렌즈"],
      ["tilt-shift|tilt shift", "틸트시프트", "일부만 초점이 맞아 미니어처처럼 보임"],
      ["14mm|16mm lens|18mm", "초광각 화각(14~18mm)"],
      ["24mm", "24mm 광각"],
      ["35mm", "35mm", "사람 눈에 가까운 자연스러운 화각(필름 35mm를 뜻하기도 함)"],
      ["50mm", "50mm 표준 렌즈"],
      ["85mm", "85mm 인물 렌즈", "얼굴이 예쁘게, 배경 흐림"],
      ["135mm|200mm", "망원 화각"],
      ["shallow depth of field|shallow dof|shallow focus", "얕은 심도", "초점 맞은 곳만 선명, 배경 흐림"],
      ["deep depth of field|deep focus", "깊은 심도", "앞뒤 모두 선명"],
      ["depth of field|dof", "피사계 심도"],
      ["bokeh", "보케, 빛망울", "흐린 배경 속 동그란 빛"],
      ["lens flare|flare", "렌즈 플레어", "강한 빛이 렌즈에 반사된 빛 번짐"],
      ["anamorphic flare|anamorphic lens flare", "아나모픽 플레어", "가로로 길게 뻗는 푸른 플레어"],
      ["chromatic aberration", "색수차", "윤곽에 색이 번짐"],
      ["vignette|vignetting", "비네팅", "화면 가장자리가 어두워짐"],
      ["barrel distortion", "배럴 왜곡", "가운데가 불룩하게 휨"],
      ["soft focus", "소프트 포커스", "전체가 부드럽게 흐림"],
      ["split diopter", "스플릿 디옵터", "앞과 뒤 두 곳에 동시에 초점"],
      ["aperture|f-stop", "조리개"],
      ["f/1.4|f1.4|f/1.8|f1.8|f/2.8", "밝은 조리개", "배경 흐림이 강함"],
      ["focal length", "초점 거리"],
      ["in focus|sharp focus", "초점이 맞은, 선명한"],
      ["out of focus|blurry|blurred", "초점이 나간, 흐린"],
      ["lens breathing", "렌즈 브리딩", "초점 이동 시 화각이 미세하게 변함"],
      ["cinema lens|cine lens", "시네마 렌즈"],
      ["vintage lens", "빈티지 렌즈"],
    ],
  ],
  [
    "light",
    [
      ["key light", "키 라이트, 주광", "주된 조명"],
      ["fill light", "필 라이트, 보조광", "그림자를 채우는 조명"],
      ["rim light|rim lighting|rim-lit", "림 라이트, 윤곽광", "뒤에서 비춰 윤곽을 빛나게"],
      ["back light|backlight|backlighting|backlit", "역광, 백라이트", "피사체 뒤에서 오는 빛"],
      ["hair light", "헤어 라이트", "머리 윤곽을 살리는 조명"],
      ["side light|side lighting|sidelit", "측광, 사이드 라이트"],
      ["top light|overhead light", "탑 라이트, 머리 위 조명"],
      ["under light|underlighting|uplighting", "아래 조명, 언더 라이트", "공포감"],
      ["practical light|practical lights|practicals", "프랙티컬 조명", "화면 안에 보이는 실제 조명(스탠드, 네온 등)"],
      ["motivated lighting|motivated light", "모티베이티드 조명", "창·램프 등 광원 근거가 있는 조명"],
      ["three-point lighting", "3점 조명", "키·필·백 라이트"],
      ["rembrandt lighting", "렘브란트 조명", "뺨에 삼각형 빛이 생기는 인물 조명"],
      ["butterfly lighting|paramount lighting", "버터플라이 조명", "코 밑에 나비 모양 그림자"],
      ["split lighting", "스플릿 조명", "얼굴 반쪽만 밝음"],
      ["loop lighting", "루프 조명"],
      ["high-key|high key|high-key lighting", "하이키", "밝고 그림자가 적은"],
      ["low-key|low key|low-key lighting", "로우키", "어둡고 명암 대비가 강한"],
      ["chiaroscuro", "키아로스쿠로", "강한 명암 대비"],
      ["hard light", "하드 라이트, 딱딱한 빛", "그림자 경계가 선명"],
      ["soft light|soft lighting", "소프트 라이트, 부드러운 빛"],
      ["diffused light|diffused lighting|diffuse", "확산광, 부드럽게 퍼진 빛"],
      ["bounce light|bounced light", "반사광, 바운스 조명"],
      ["natural light|natural lighting", "자연광"],
      ["available light|ambient light", "현장광, 주변광"],
      ["golden hour|magic hour", "골든아워", "해 뜰 녘·해 질 녘의 따뜻하고 낮은 빛"],
      ["blue hour", "블루아워", "해 진 직후·해 뜨기 전의 푸른 시간"],
      ["direct sunlight|harsh sunlight", "직사광선"],
      ["dappled light|dappled sunlight", "나뭇잎 사이로 얼룩진 빛"],
      ["volumetric light|volumetric lighting|volumetric", "볼류메트릭 라이트", "빛줄기가 공기 중에 보이는 빛"],
      ["god rays|crepuscular rays|light rays|sunbeams", "빛내림, 갓레이", "구름·창 사이로 쏟아지는 빛줄기"],
      ["light shafts|shafts of light", "빛줄기"],
      ["neon light|neon lights|neon", "네온 조명"],
      ["neon-lit|neon lit", "네온 불빛이 비치는"],
      ["tungsten|tungsten light", "텅스텐 조명", "따뜻한 주황빛"],
      ["fluorescent|fluorescent light", "형광등"],
      ["candlelight|candle light", "촛불 조명"],
      ["moonlight|moonlit", "달빛"],
      ["firelight", "불빛, 모닥불 빛"],
      ["silhouette|silhouetted", "실루엣", "역광으로 형체만 검게"],
      ["specular highlight|specular highlights", "하이라이트 반사", "반짝이는 빛 반사점"],
      ["color temperature", "색온도"],
      ["warm light|warm lighting", "따뜻한 빛"],
      ["cool light|cold light|cool lighting", "차가운 빛"],
      ["mixed lighting", "혼합 조명", "색온도가 다른 빛이 섞임"],
      ["studio lighting", "스튜디오 조명"],
      ["softbox", "소프트박스"],
      ["ring light", "링 라이트"],
      ["spotlight|spot light", "스포트라이트"],
      ["strobe|strobe light", "스트로브"],
      ["flicker|flickering", "깜빡이는"],
      ["light leak|light leaks", "빛 샘, 라이트 릭", "필름에 빛이 새어 든 붉은 번짐"],
      ["caustics", "커스틱", "물·유리를 통과한 빛의 일렁이는 무늬"],
      ["glow|glowing", "빛나는, 발광하는"],
      ["bioluminescent|bioluminescence", "생물 발광"],
      ["lit by|illuminated by", "~에 비친, ~로 밝혀진"],
      ["cinematic lighting", "시네마틱 조명", "영화처럼 연출된 조명"],
      ["dramatic lighting", "극적인 조명"],
    ],
  ],
  [
    "color",
    [
      ["color grading|color grade|colour grading", "색보정, 컬러 그레이딩"],
      ["teal and orange|orange and teal", "틸 앤 오렌지", "청록 그림자·주황 피부톤의 할리우드식 보정"],
      ["desaturated", "채도를 낮춘"],
      ["saturated|highly saturated", "채도가 높은"],
      ["vibrant|vivid", "선명하고 강렬한"],
      ["muted colors|muted tones|muted", "차분한 색감"],
      ["pastel|pastel colors", "파스텔 톤"],
      ["monochrome|monochromatic", "모노톤, 단색조"],
      ["black and white|b&w", "흑백"],
      ["sepia", "세피아"],
      ["high contrast", "고대비"],
      ["low contrast", "저대비"],
      ["crushed blacks", "눌린 블랙", "어두운 부분이 뭉개진 진한 검정"],
      ["lifted blacks|faded", "들뜬 블랙", "검정이 회색빛으로 바랜 필름 느낌"],
      ["halation", "헐레이션", "밝은 부분 주변이 붉게 번지는 필름 효과"],
      ["bleach bypass", "블리치 바이패스", "채도 낮고 대비 강한 거친 필름 톤"],
      ["day for night", "데이 포 나이트", "낮에 찍어 밤처럼 보이게"],
      ["split toning", "스플릿 토닝", "밝은 곳과 어두운 곳에 다른 색"],
      ["color palette|colour palette", "색 팔레트, 컬러 팔레트"],
      ["complementary colors", "보색"],
      ["earth tones", "어스 톤", "흙·나무 같은 자연색"],
      ["neon colors", "네온 컬러"],
      ["kodak portra|portra 400", "코닥 포트라", "따뜻하고 부드러운 인물용 필름 톤"],
      ["kodak ektachrome|ektachrome", "엑타크롬", "선명한 슬라이드 필름 톤"],
      ["fujifilm|fuji film|fuji superia", "후지필름 톤", "초록빛이 도는 필름 색감"],
      ["cinestill|cinestill 800t", "시네스틸 800T", "야간 네온 헐레이션 필름 톤"],
      ["lut", "LUT", "색보정 프리셋"],
      ["hdr", "HDR", "밝은 곳과 어두운 곳을 모두 살림"],
      ["crimson", "진홍색"],
      ["scarlet", "주홍색, 선홍색"],
      ["burgundy|maroon", "버건디, 적갈색"],
      ["teal", "청록색"],
      ["cyan", "시안, 청록"],
      ["magenta", "마젠타, 자홍색"],
      ["amber", "호박색, 앰버"],
      ["emerald", "에메랄드빛"],
      ["ivory", "아이보리"],
      ["beige", "베이지"],
      ["charcoal", "차콜, 짙은 회색"],
      ["gold|golden", "금색의, 황금빛"],
      ["silver", "은색의"],
      ["pale", "창백한, 옅은"],
    ],
  ],
  [
    "film",
    [
      ["film grain|grain|grainy", "필름 그레인, 입자감"],
      ["35mm film|shot on 35mm|35mm photograph", "35mm 필름", "35mm 필름으로 찍은 질감"],
      ["16mm film|16mm", "16mm 필름", "입자가 굵고 다큐 같은 질감"],
      ["super 8|super8", "슈퍼 8", "홈비디오 같은 8mm 필름"],
      ["70mm|imax", "70mm·IMAX", "초고해상도 대형 필름"],
      ["vhs|vhs tape", "VHS", "옛날 비디오테이프 화질"],
      ["analog|analogue", "아날로그"],
      ["noise", "노이즈"],
      ["scan lines|scanlines", "주사선"],
      ["crt|crt monitor", "CRT 브라운관"],
      ["glitch|glitch effect", "글리치", "디지털 오류 효과"],
      ["motion blur", "모션 블러", "움직임 잔상"],
      ["shutter angle|180-degree shutter|180 degree shutter", "셔터 앵글", "움직임 잔상의 양"],
      ["frame rate|fps", "프레임 레이트"],
      ["24fps|24 fps", "24프레임", "영화 같은 움직임"],
      ["60fps|60 fps|high frame rate|hfr", "60프레임, 고프레임", "매끄러운 움직임"],
      ["letterbox|letterboxed", "레터박스", "위아래 검은 띠"],
      ["aspect ratio|ar", "화면비"],
      ["2.39:1|2.35:1|cinemascope|scope", "시네마스코프", "가로로 긴 영화 화면비"],
      ["16:9", "16:9 가로 화면"],
      ["9:16|vertical video", "9:16 세로 화면"],
      ["1:1|square", "1:1 정사각형"],
      ["4k|4k resolution|uhd", "4K 해상도"],
      ["8k|8k resolution", "8K 해상도"],
      ["raw|raw photo", "RAW, 원본"],
      ["photograph|photo", "사진"],
      ["polaroid", "폴라로이드"],
      ["disposable camera", "일회용 카메라 감성"],
      ["dslr", "DSLR"],
      ["iphone photo|shot on iphone", "아이폰 사진 감성"],
      ["cctv|security camera|surveillance footage", "CCTV 화면"],
      ["found footage", "파운드 푸티지", "주운 영상처럼 거친 기록 영상"],
      ["documentary footage|documentary style", "다큐 촬영 스타일"],
      ["archival footage", "아카이브 영상, 옛 기록 영상"],
      ["sharp|razor sharp", "선명한"],
      ["high detail|highly detailed|intricate details|ultra detailed", "디테일이 풍부한"],
      ["masterpiece|best quality", "최고 품질(품질 태그)"],
    ],
  ],
  [
    "composition",
    [
      ["rule of thirds", "3분할 구도"],
      ["symmetry|symmetrical|symmetrical composition", "대칭 구도"],
      ["centered composition|centered|center frame", "중앙 구도"],
      ["leading lines", "유도선", "시선을 이끄는 선"],
      ["negative space", "여백"],
      ["framing", "프레이밍, 화면 구성"],
      ["frame within a frame", "프레임 속 프레임", "문·창 등으로 다시 가두는 구도"],
      ["foreground", "전경"],
      ["midground|middle ground", "중경"],
      ["background", "배경"],
      ["layered composition|depth layers", "레이어드 구도", "앞·중간·뒤 층이 있는 구도"],
      ["golden ratio", "황금 비율"],
      ["headroom", "헤드룸", "머리 위 여백"],
      ["lead room|nose room|looking room", "리드룸", "시선 방향의 여백"],
      ["minimalist composition|minimal composition", "미니멀 구도"],
      ["asymmetry|asymmetrical", "비대칭"],
      ["diagonal composition", "대각선 구도"],
      ["reflection|reflections", "반사, 반영"],
      ["mirror shot|mirror reflection", "거울 반사 샷"],
      ["depth", "깊이감"],
      ["scale|sense of scale", "스케일감"],
      ["close to camera", "카메라 가까이"],
      ["in the distance", "멀리, 먼 곳에"],
      ["in the frame|in frame", "화면 안에"],
      ["off-screen|out of frame", "화면 밖"],
    ],
  ],
  [
    "cg",
    [
      ["3d render|3d rendering|render", "3D 렌더"],
      ["cgi|cg", "CGI, 컴퓨터 그래픽"],
      ["octane render|octane", "옥테인 렌더", "사실적인 GPU 렌더러"],
      ["redshift", "레드시프트 렌더러"],
      ["arnold render|arnold", "아놀드 렌더러"],
      ["unreal engine|unreal engine 5|ue5", "언리얼 엔진", "실시간 게임 엔진 그래픽"],
      ["cinema 4d|c4d", "시네마 4D"],
      ["blender", "블렌더"],
      ["houdini", "후디니", "시뮬레이션·이펙트 툴"],
      ["ray tracing|raytracing|ray traced", "레이 트레이싱", "빛의 경로를 계산한 사실적 반사·그림자"],
      ["path tracing", "패스 트레이싱"],
      ["global illumination|gi", "전역 조명(GI)", "반사광까지 계산"],
      ["ambient occlusion|ao", "앰비언트 오클루전", "틈새에 생기는 부드러운 그림자"],
      ["subsurface scattering|sss", "표면하 산란(SSS)", "피부·밀랍처럼 빛이 속으로 스며드는 표현"],
      ["pbr|physically based rendering|pbr materials", "물리 기반 렌더링(PBR)"],
      ["displacement|displacement map", "디스플레이스먼트", "표면을 실제로 울퉁불퉁하게"],
      ["normal map", "노멀 맵"],
      ["texture|textured", "질감, 텍스처"],
      ["material|materials", "재질, 머티리얼"],
      ["shader", "셰이더"],
      ["toon shader|toon shading", "툰 셰이더", "만화 같은 음영"],
      ["cel shading|cel-shaded|cel shaded", "셀 셰이딩", "만화풍 단계 음영"],
      ["low poly|low-poly", "로우 폴리", "각진 단순한 3D"],
      ["high poly|high-poly", "하이 폴리", "정밀한 3D"],
      ["voxel|voxel art", "복셀", "정육면체 블록 3D"],
      ["clay render|clay model", "클레이 렌더", "흰 점토처럼 재질 없이"],
      ["wireframe", "와이어프레임"],
      ["matte painting", "매트 페인팅", "배경을 그림으로 합성"],
      ["compositing|composite", "합성, 컴포지팅"],
      ["green screen|chroma key|chromakey", "크로마키, 그린 스크린"],
      ["vfx|visual effects", "VFX, 시각 효과"],
      ["particle simulation|particles", "파티클", "입자 시뮬레이션"],
      ["fluid simulation", "유체 시뮬레이션"],
      ["cloth simulation", "천 시뮬레이션"],
      ["smoke simulation", "연기 시뮬레이션"],
      ["destruction|destruction simulation", "파괴 시뮬레이션"],
      ["volumetric fog", "볼류메트릭 포그", "공간에 깔린 입체 안개"],
      ["isometric|isometric view", "아이소메트릭", "원근 없는 비스듬한 위 시점"],
      ["orthographic|orthographic view", "직교 투영", "원근 없는 설계도 시점"],
      ["turntable|turntable render", "턴테이블", "제자리에서 360도 회전하며 보여 줌"],
      ["turnaround sheet|turnaround|character turnaround", "턴어라운드 시트", "앞·옆·뒤 모습 설정화"],
      ["character sheet|model sheet|reference sheet", "캐릭터 시트, 설정화"],
      ["t-pose", "T포즈"],
      ["a-pose", "A포즈"],
      ["rigging|rigged", "리깅", "뼈대를 심어 움직이게"],
      ["motion capture|mocap", "모션 캡처"],
      ["keyframe animation|keyframe", "키프레임 애니메이션"],
      ["photogrammetry", "포토그래메트리", "사진으로 만든 3D 스캔"],
      ["gaussian splatting|3d gaussian splatting|3dgs", "가우시안 스플래팅", "사진으로 만든 입체 장면"],
      ["nerf", "NeRF", "사진 기반 3D 장면 재구성"],
      ["hdri", "HDRI", "주변 환경 조명 이미지"],
      ["cyclorama|cyc|infinite background|seamless background", "호리존트", "모서리가 안 보이는 무한 배경"],
      ["studio backdrop|backdrop", "배경지, 스튜디오 백드롭"],
      ["product render", "제품 렌더"],
      ["hologram", "홀로그램"],
      ["digital human|metahuman", "디지털 휴먼"],
      ["avatar", "아바타"],
    ],
  ],
  [
    "style",
    [
      ["cinematic", "시네마틱, 영화 같은"],
      ["cinematic still|film still|movie still", "영화 스틸컷"],
      ["photorealistic|photo-realistic|photoreal", "사진처럼 사실적인"],
      ["hyperrealistic|hyper-realistic|hyperrealism", "극사실적인"],
      ["realistic", "사실적인"],
      ["surreal|surrealism|surrealist", "초현실적인"],
      ["dreamlike|dreamy", "꿈같은"],
      ["ethereal", "몽환적인, 천상의"],
      ["film noir|noir", "필름 누아르", "흑백·그림자·범죄극 분위기"],
      ["neo-noir|neon noir", "네오 누아르", "네온 컬러의 현대 누아르"],
      ["cyberpunk", "사이버펑크"],
      ["steampunk", "스팀펑크"],
      ["retro", "레트로"],
      ["vintage", "빈티지"],
      ["y2k|y2k aesthetic", "Y2K", "2000년대 초 감성"],
      ["vaporwave", "베이퍼웨이브", "80·90년대 파스텔 네온 감성"],
      ["synthwave|retrowave", "신스웨이브", "80년대 네온 레트로"],
      ["minimalist|minimalism|minimal", "미니멀한"],
      ["maximalist|maximalism", "맥시멀한"],
      ["brutalist|brutalism", "브루탈리즘", "거친 콘크리트 건축 양식"],
      ["editorial|editorial photography", "에디토리얼, 화보풍"],
      ["fashion editorial", "패션 화보"],
      ["fashion photography", "패션 사진"],
      ["commercial|commercial photography|advertising", "광고 사진"],
      ["product photography|product shot", "제품 사진"],
      ["still life", "정물"],
      ["documentary", "다큐멘터리"],
      ["street photography", "스트리트 사진"],
      ["portrait|portrait photography", "인물 사진, 초상"],
      ["fine art", "파인 아트"],
      ["abstract", "추상적인"],
      ["conceptual|concept art", "콘셉트 아트"],
      ["key visual|kv", "키 비주얼", "대표 홍보 이미지"],
      ["poster|movie poster", "포스터"],
      ["anime|anime style", "애니메이션풍"],
      ["manga|manga style", "만화풍"],
      ["studio ghibli style|ghibli style|ghibli", "지브리풍"],
      ["pixar style|pixar", "픽사풍 3D"],
      ["disney style", "디즈니풍"],
      ["claymation|clay animation", "클레이 애니메이션"],
      ["stop motion|stop-motion", "스톱모션"],
      ["watercolor|watercolour", "수채화"],
      ["oil painting", "유화"],
      ["ink|ink drawing|ink wash", "잉크화, 수묵"],
      ["sketch|pencil sketch", "스케치"],
      ["line art", "라인 아트"],
      ["collage", "콜라주"],
      ["mixed media", "혼합 매체"],
      ["double exposure", "이중 노출"],
      ["long exposure", "장노출", "빛·움직임이 긴 궤적으로"],
      ["infrared|infrared photography", "적외선 사진"],
      ["thermal|thermal imaging", "열화상"],
      ["x-ray", "엑스레이"],
      ["holographic", "홀로그래픽"],
      ["iridescent", "이리데선트, 무지갯빛", "보는 각도에 따라 색이 변하는"],
      ["chrome|chromed", "크롬, 금속 광택"],
      ["glossy", "광택 있는"],
      ["matte", "무광"],
      ["metallic", "금속성의"],
      ["translucent", "반투명한"],
      ["transparent", "투명한"],
      ["frosted glass", "불투명 유리, 간유리"],
      ["glass|glassy", "유리, 유리 같은"],
      ["liquid metal", "액체 금속"],
      ["dark fantasy", "다크 판타지"],
      ["high fantasy|fantasy", "판타지"],
      ["sci-fi|science fiction", "SF, 공상과학"],
      ["dystopian|dystopia", "디스토피아"],
      ["utopian", "유토피아적인"],
      ["post-apocalyptic", "포스트 아포칼립스", "문명 붕괴 이후"],
      ["gothic", "고딕"],
      ["baroque", "바로크"],
      ["art deco", "아르데코"],
      ["art nouveau", "아르누보"],
      ["bauhaus", "바우하우스"],
      ["pop art", "팝 아트"],
      ["ukiyo-e", "우키요에"],
      ["music video|mv", "뮤직비디오"],
      ["k-pop|k-pop music video", "K팝, K팝 뮤직비디오"],
      ["tv commercial|commercial spot", "TV 광고"],
      ["trailer|movie trailer", "예고편"],
      ["title sequence|opening title", "타이틀 시퀀스"],
      ["lookbook", "룩북"],
      ["mood board|moodboard", "무드보드"],
      ["storyboard", "스토리보드, 콘티"],
      ["sticker|die-cut sticker", "스티커"],
      ["logo|logotype", "로고"],
      ["typography", "타이포그래피"],
      ["infographic", "인포그래픽"],
      ["flat design|flat illustration", "플랫 디자인"],
      ["isometric illustration", "아이소메트릭 일러스트"],
      ["vector|vector art", "벡터 아트"],
      ["pixel art", "픽셀 아트"],
      ["graffiti", "그래피티"],
      ["bokeh background", "배경 빛망울"],
    ],
  ],
  [
    "mood",
    [
      ["moody", "분위기 있는, 무디한"],
      ["atmospheric", "대기감 있는, 분위기 있는"],
      ["melancholic|melancholy", "우울한, 쓸쓸한"],
      ["nostalgic", "향수를 부르는"],
      ["serene", "고요한"],
      ["tranquil|peaceful", "평화로운"],
      ["tense", "긴장감 있는"],
      ["eerie|creepy", "으스스한"],
      ["ominous", "불길한"],
      ["whimsical", "기발하고 동화 같은"],
      ["playful", "장난스러운"],
      ["dramatic", "극적인"],
      ["epic", "웅장한, 서사적인"],
      ["intimate", "친밀한, 내밀한"],
      ["lonely|solitary", "외로운, 고독한"],
      ["hopeful", "희망찬"],
      ["dynamic", "역동적인"],
      ["energetic", "에너지 넘치는"],
      ["calm", "차분한"],
      ["mysterious", "신비로운"],
      ["romantic", "낭만적인"],
      ["gritty", "거친, 투박한"],
      ["raw", "날것의"],
      ["elegant", "우아한"],
      ["luxurious|luxury", "고급스러운, 럭셔리"],
      ["cozy", "아늑한"],
      ["chaotic", "혼돈스러운"],
      ["majestic", "장엄한"],
      ["haunting", "잊히지 않는, 뇌리에 남는"],
      ["bittersweet", "씁쓸하고 달콤한"],
      ["cinematic mood", "영화 같은 분위기"],
    ],
  ],
  [
    "scene",
    [
      ["rain|raining|rainy", "비, 비 오는"],
      ["heavy rain|downpour", "폭우"],
      ["light rain|drizzle", "가랑비, 이슬비"],
      ["fog|foggy", "안개, 안개 낀"],
      ["mist|misty", "옅은 안개"],
      ["haze|hazy", "연무, 뿌연"],
      ["smoke|smoky", "연기"],
      ["dust|dusty", "먼지"],
      ["snow|snowy|snowfall", "눈, 눈 내리는"],
      ["blizzard", "눈보라"],
      ["storm|stormy", "폭풍"],
      ["lightning", "번개"],
      ["wind|windy", "바람"],
      ["puddle|puddles", "웅덩이"],
      ["wet asphalt|wet street|rain-soaked street", "젖은 아스팔트"],
      ["sunset", "해 질 녘, 노을"],
      ["sunrise", "해돋이"],
      ["dusk", "땅거미, 해 질 무렵"],
      ["dawn", "새벽"],
      ["night|at night|nighttime", "밤"],
      ["twilight", "황혼"],
      ["midday|noon", "한낮"],
      ["overcast|overcast sky", "흐린 하늘"],
      ["cloudy", "구름 낀"],
      ["clear sky", "맑은 하늘"],
      ["starry sky|starry night", "별이 빛나는 하늘"],
      ["aurora|northern lights", "오로라"],
      ["underwater", "물속, 수중"],
      ["desert", "사막"],
      ["forest", "숲"],
      ["jungle", "정글"],
      ["ocean|sea", "바다"],
      ["beach", "해변"],
      ["mountain|mountains", "산"],
      ["cityscape", "도시 풍경"],
      ["skyline", "스카이라인"],
      ["alley|alleyway|back alley", "골목"],
      ["rooftop", "옥상"],
      ["subway|subway station|metro", "지하철"],
      ["highway|freeway", "고속도로"],
      ["street", "거리"],
      ["crosswalk", "횡단보도"],
      ["neon sign|neon signs", "네온사인"],
      ["billboard", "광고판"],
      ["interior|indoors", "실내"],
      ["exterior|outdoors", "실외"],
      ["studio", "스튜디오"],
      ["warehouse", "창고"],
      ["abandoned", "버려진, 폐허가 된"],
      ["ruins", "폐허, 유적"],
      ["cathedral", "대성당"],
      ["temple", "사원, 절"],
      ["palace", "궁전"],
      ["hanok", "한옥"],
      ["seoul", "서울"],
      ["tokyo", "도쿄"],
      ["space|outer space", "우주"],
      ["nebula", "성운"],
      ["planet", "행성"],
      ["void|black void", "허공, 검은 공간"],
      ["infinite white space|white void", "끝없는 흰 공간"],
      ["field|meadow", "들판, 초원"],
      ["flowers|flower field", "꽃, 꽃밭"],
      ["cherry blossoms|sakura", "벚꽃"],
      ["autumn leaves|fall foliage", "단풍"],
      ["waterfall", "폭포"],
      ["lake", "호수"],
      ["river", "강"],
      ["waves", "파도"],
      ["cliff", "절벽"],
      ["cave", "동굴"],
      ["bridge", "다리"],
      ["tunnel", "터널"],
      ["stage|concert stage", "무대"],
      ["crowd", "군중, 관객"],
    ],
  ],
  [
    "motion",
    [
      ["walking|walks|walk", "걷는"],
      ["running|runs|run", "달리는"],
      ["dancing|dances|dance", "춤추는"],
      ["spinning|spins", "빙글빙글 도는"],
      ["turning|turns", "도는, 돌아서는"],
      ["turns around|turning around", "뒤돌아보는"],
      ["jumping|jumps", "뛰어오르는"],
      ["floating|floats", "떠 있는, 부유하는"],
      ["falling|falls", "떨어지는"],
      ["flying|flies", "날아가는"],
      ["drifting|drifts", "떠다니는, 흘러가는"],
      ["swaying|sways", "흔들리는"],
      ["flowing|flows", "흐르는, 흩날리는"],
      ["rippling|ripples", "잔물결이 이는"],
      ["fluttering|flutters", "펄럭이는, 나풀거리는"],
      ["exploding|explodes|explosion", "폭발하는"],
      ["shattering|shatters", "산산이 부서지는"],
      ["melting|melts", "녹아내리는"],
      ["dissolving|dissolves", "흩어져 사라지는"],
      ["morphing|morphs", "모핑, 다른 형태로 변하는"],
      ["transforming|transforms", "변신하는"],
      ["emerging|emerges", "나타나는, 모습을 드러내는"],
      ["fading in", "서서히 나타나는"],
      ["fading out", "서서히 사라지는"],
      ["looking at the camera|looking at camera|looks at the camera", "카메라를 바라보는"],
      ["looking away", "다른 곳을 바라보는"],
      ["smiling|smiles", "미소 짓는"],
      ["crying", "우는"],
      ["laughing", "웃는"],
      ["screaming", "소리치는"],
      ["whispering", "속삭이는"],
      ["sitting", "앉아 있는"],
      ["standing", "서 있는"],
      ["lying|lying down", "누워 있는"],
      ["kneeling", "무릎 꿇은"],
      ["reaching out", "손을 뻗는"],
      ["holding", "들고 있는"],
      ["hair blowing in the wind|wind-blown hair|windswept hair", "바람에 날리는 머리카락"],
      ["fabric flowing|flowing fabric|flowing dress", "흩날리는 옷자락"],
      ["splashing|splash", "물이 튀는"],
      ["pouring", "쏟아지는, 붓는"],
      ["slowly|slow", "천천히"],
      ["quickly|fast", "빠르게"],
      ["gently", "부드럽게"],
      ["suddenly", "갑자기"],
      ["seamless loop|looping|loop", "끊김 없는 반복(루프)"],
    ],
  ],
  [
    "edit",
    [
      ["match cut", "매치 컷", "모양·움직임이 이어지게 전환"],
      ["jump cut", "점프 컷", "같은 구도에서 시간만 튀게"],
      ["cross dissolve|dissolve", "디졸브", "겹치며 전환"],
      ["fade to black", "페이드 아웃(검은 화면)"],
      ["fade from black|fade in", "페이드 인"],
      ["whip transition", "휩 전환", "휩 팬으로 장면 전환"],
      ["smash cut", "스매시 컷", "급격한 대비 전환"],
      ["montage", "몽타주"],
      ["split screen", "분할 화면"],
      ["seamless transition", "매끄러운 전환"],
      ["transition", "장면 전환"],
      ["cut to", "~로 컷 전환"],
      ["scene|shot", "장면, 샷"],
      ["sequence", "시퀀스"],
      ["beat", "비트, 짧은 순간"],
    ],
  ],
  [
    "audio",
    [
      ["ambient sound|ambience|ambient", "환경음, 앰비언스"],
      ["diegetic sound", "극중 소리", "화면 속에서 나는 소리"],
      ["sound effects|sfx", "효과음"],
      ["dialogue|dialog", "대사"],
      ["voiceover|voice-over|narration", "보이스오버, 내레이션"],
      ["background music|bgm|score", "배경 음악"],
      ["music", "음악"],
      ["crowd cheering", "관객 환호"],
      ["footsteps", "발소리"],
      ["rain sounds", "빗소리"],
      ["silence|silent", "정적, 무음"],
      ["lip sync|lip-sync|lipsync", "립싱크"],
      ["singing|sings", "노래하는"],
      ["heartbeat", "심장 박동 소리"],
      ["whoosh", "휙 하는 소리"],
      ["bass drop", "베이스 드롭"],
    ],
  ],
  [
    "prompt",
    [
      ["negative prompt", "네거티브 프롬프트", "나오지 않게 할 요소"],
      ["seed", "시드", "같은 값이면 비슷한 결과"],
      ["style reference", "스타일 레퍼런스"],
      ["character reference", "캐릭터 레퍼런스"],
      ["reference image", "레퍼런스 이미지"],
      ["consistency|consistent character", "일관성, 같은 캐릭터 유지"],
      ["upscale|upscaled", "업스케일, 고해상도 확대"],
      ["inpainting", "인페인팅", "일부만 다시 그리기"],
      ["outpainting", "아웃페인팅", "화면 밖으로 확장"],
      ["image to video|image-to-video|i2v", "이미지→영상"],
      ["text to video|text-to-video|t2v", "텍스트→영상"],
      ["first frame|start frame", "첫 프레임"],
      ["last frame|end frame", "마지막 프레임"],
      ["same character", "같은 캐릭터"],
      ["no text|without text", "글자 없이"],
      ["watermark", "워터마크"],
    ],
  ],
  [
    "common",
    [
      ["woman|women", "여자"],
      ["man|men", "남자"],
      ["girl", "소녀, 여자아이"],
      ["boy", "소년, 남자아이"],
      ["child|children|kid|kids", "아이"],
      ["person|people", "사람"],
      ["character", "캐릭터, 인물"],
      ["model", "모델"],
      ["dancer", "댄서, 무용수"],
      ["singer", "가수"],
      ["actor|actress", "배우"],
      ["crowd of people", "사람들, 군중"],
      ["face", "얼굴"],
      ["eyes|eye", "눈"],
      ["lips|lip", "입술"],
      ["hands|hand", "손"],
      ["skin", "피부"],
      ["hair", "머리카락"],
      ["long hair", "긴 머리"],
      ["short hair", "짧은 머리"],
      ["expression", "표정"],
      ["pose|posing", "포즈"],
      ["dress", "드레스, 원피스"],
      ["silk dress", "실크 드레스"],
      ["suit", "정장"],
      ["jacket", "재킷"],
      ["leather jacket", "가죽 재킷"],
      ["coat|trench coat", "코트, 트렌치코트"],
      ["shirt", "셔츠"],
      ["t-shirt", "티셔츠"],
      ["hoodie", "후드티"],
      ["jeans", "청바지"],
      ["skirt", "치마"],
      ["sneakers", "운동화"],
      ["boots", "부츠"],
      ["hat", "모자"],
      ["sunglasses", "선글라스"],
      ["jewelry|jewellery", "장신구"],
      ["mask", "가면, 마스크"],
      ["armor|armour", "갑옷"],
      ["uniform", "제복"],
      ["hanbok", "한복"],
      ["red", "빨간"],
      ["blue", "파란"],
      ["green", "초록"],
      ["yellow", "노란"],
      ["orange", "주황"],
      ["purple|violet", "보라"],
      ["pink", "분홍"],
      ["white", "흰"],
      ["black", "검은"],
      ["gray|grey", "회색"],
      ["brown", "갈색"],
      ["dark", "어두운"],
      ["bright", "밝은"],
      ["light", "빛, 밝은, 가벼운"],
      ["shadow|shadows", "그림자"],
      ["huge|giant|gigantic|massive", "거대한"],
      ["tiny|small|little", "작은"],
      ["big|large", "큰"],
      ["tall", "키 큰, 높은"],
      ["old", "오래된, 나이 든"],
      ["young", "젊은"],
      ["new", "새로운"],
      ["beautiful|gorgeous", "아름다운"],
      ["cute|adorable", "귀여운"],
      ["cool", "멋진, 시원한"],
      ["futuristic", "미래적인"],
      ["ancient", "고대의"],
      ["modern", "현대적인"],
      ["traditional", "전통적인"],
      ["korean", "한국의, 한국인"],
      ["wet", "젖은"],
      ["soft", "부드러운"],
      ["smooth", "매끄러운"],
      ["rough", "거친"],
      ["shiny", "반짝이는"],
      ["colorful|colourful", "다채로운"],
      ["empty", "텅 빈"],
      ["crowded", "붐비는"],
      ["quiet", "조용한"],
      ["busy", "분주한"],
      ["city", "도시"],
      ["room", "방"],
      ["window", "창문"],
      ["door", "문"],
      ["wall", "벽"],
      ["floor", "바닥"],
      ["table", "테이블"],
      ["chair", "의자"],
      ["car", "자동차"],
      ["motorcycle", "오토바이"],
      ["train", "기차"],
      ["building|buildings", "건물"],
      ["tree|trees", "나무"],
      ["sky", "하늘"],
      ["sun", "해, 태양"],
      ["moon", "달"],
      ["stars|star", "별"],
      ["cloud|clouds", "구름"],
      ["water", "물"],
      ["fire|flames", "불, 불꽃"],
      ["ice", "얼음"],
      ["petals|petal", "꽃잎"],
      ["butterfly|butterflies", "나비"],
      ["bird|birds", "새"],
      ["cat", "고양이"],
      ["dog", "개"],
      ["horse", "말"],
      ["dragon", "용"],
      ["robot", "로봇"],
      ["mirror", "거울"],
      ["phone|smartphone", "휴대폰"],
      ["camera", "카메라"],
      ["bottle", "병"],
      ["perfume bottle", "향수병"],
      ["cup|mug", "컵"],
      ["food", "음식"],
      ["cake", "케이크"],
      ["coffee", "커피"],
      ["with", "~와 함께, ~을 가진"],
      ["wearing", "~을 입은"],
      ["holding a", "~을 든"],
      ["surrounded by", "~에 둘러싸인"],
      ["in front of", "~앞에"],
      ["behind", "~뒤에"],
      ["next to|beside", "~옆에"],
      ["through", "~을 지나, ~사이로"],
      ["against", "~을 배경으로, ~에 기대어"],
      ["under", "~아래에"],
      ["above|over", "~위에"],
      ["inside", "~안에"],
      ["across", "~을 가로질러"],
      ["toward|towards", "~을 향해"],
      ["while", "~하는 동안"],
      ["background of", "~을 배경으로"],
      ["detailed", "디테일한"],
      ["high quality", "고품질"],
      ["ultra realistic", "극사실적인"],
      ["scene of", "~의 장면"],
      ["view of", "~의 모습, ~을 바라본 모습"],
    ],
  ],
];

export type GlossaryEntry = {
  /** 대표 영어 표현 */
  en: string;
  /** 매칭에 쓰는 모든 영어 표현(소문자) */
  forms: string[];
  /** 한국어 뜻들 (첫 번째가 대표) */
  ko: string[];
  note?: string;
  category: GlossaryCategory;
};

/** 대소문자·하이픈·공백 차이를 없앤 비교용 키 */
export function normalizeTerm(s: string): string {
  return s
    .toLowerCase()
    .replace(/[’`]/g, "'")
    .replace(/[‐-―]/g, "-")
    .replace(/[^a-z0-9'./:&+\-\s]/g, " ")
    .replace(/[-\s]+/g, " ")
    .trim();
}

export const GLOSSARY: GlossaryEntry[] = GROUPS.flatMap(([category, items]) =>
  items.map(([en, ko, note]) => {
    const forms = en.split("|").map((f) => f.trim()).filter(Boolean);
    return {
      en: forms[0],
      forms: forms.map((f) => f.toLowerCase()),
      ko: ko.split(",").map((k) => k.trim()).filter(Boolean),
      note,
      category,
    };
  }),
);

const byForm = new Map<string, GlossaryEntry>();
let longestForm = 1;
for (const e of GLOSSARY) {
  for (const f of e.forms) {
    const key = normalizeTerm(f);
    if (!key) continue;
    // 먼저 나온(더 구체적인 분야의) 뜻을 우선
    if (!byForm.has(key)) byForm.set(key, e);
    longestForm = Math.max(longestForm, key.split(" ").length);
  }
}

/** 영어 단어의 기본형 후보 (복수·진행형·과거형 등) */
export function englishLemmas(word: string): string[] {
  const w = word.toLowerCase();
  const out = new Set<string>([w]);
  if (w.length > 3) {
    if (w.endsWith("ies")) out.add(`${w.slice(0, -3)}y`);
    if (w.endsWith("es")) out.add(w.slice(0, -2));
    if (w.endsWith("s") && !w.endsWith("ss")) out.add(w.slice(0, -1));
    if (w.endsWith("ing")) {
      const stem = w.slice(0, -3);
      out.add(stem);
      out.add(`${stem}e`);
      if (/(.)\1$/.test(stem)) out.add(stem.slice(0, -1));
    }
    if (w.endsWith("ed")) {
      const stem = w.slice(0, -2);
      out.add(stem);
      out.add(w.slice(0, -1));
      if (/(.)\1$/.test(stem)) out.add(stem.slice(0, -1));
      if (w.endsWith("ied")) out.add(`${w.slice(0, -3)}y`);
    }
    if (w.endsWith("ly")) out.add(w.slice(0, -2));
    if (w.endsWith("er")) out.add(w.slice(0, -2));
    if (w.endsWith("est")) out.add(w.slice(0, -3));
  }
  return [...out];
}

/** 표현 하나를 용어집에서 찾기 (기본형까지 시도) */
export function glossaryLookup(phrase: string): GlossaryEntry | null {
  const key = normalizeTerm(phrase);
  if (!key) return null;
  const direct = byForm.get(key);
  if (direct) return direct;
  const words = key.split(" ");
  const last = words.pop()!;
  for (const lemma of englishLemmas(last)) {
    const hit = byForm.get([...words, lemma].join(" "));
    if (hit) return hit;
  }
  return null;
}

export type WordToken = { text: string; start: number; end: number };

/** 영어·숫자 단어 단위로 나누기 (어퍼스트로피·하이픈·소수점 포함) */
export function tokenizeEnglish(text: string): WordToken[] {
  const out: WordToken[] = [];
  const re = /[A-Za-z0-9]+(?:['’.\-/:][A-Za-z0-9]+)*/g;
  for (let m = re.exec(text); m; m = re.exec(text)) out.push({ text: m[0], start: m.index, end: m.index + m[0].length });
  return out;
}

/**
 * index 번째 단어를 포함하는 가장 긴 용어를 찾기.
 * 예) "slow dolly zoom" 에서 "dolly"에 올리면 "dolly zoom"
 */
export function glossaryPhraseAt(tokens: WordToken[], index: number, text: string): { entry: GlossaryEntry; start: number; end: number } | null {
  const maxN = Math.min(longestForm, 5);
  for (let n = maxN; n >= 1; n--) {
    for (let from = Math.max(0, index - n + 1); from <= index; from++) {
      const to = from + n - 1;
      if (to >= tokens.length) continue;
      // 문장부호(쉼표 등)를 넘는 구절은 제외
      const between = text.slice(tokens[from].start, tokens[to].end);
      if (/[,;.!?，。；\n]/.test(between.replace(/(\d)\.(\d)/g, "$1$2"))) continue;
      const entry = glossaryLookup(between);
      if (entry) return { entry, start: tokens[from].start, end: tokens[to].end };
    }
  }
  return null;
}

/** 한국어로 찾기 (한→영 단어 추천용) — 정확히 같은 뜻 먼저, 그다음 포함 */
export function glossaryByKorean(query: string, limit = 8): GlossaryEntry[] {
  const q = query.replace(/\s+/g, "").trim();
  if (!q) return [];
  const exact: GlossaryEntry[] = [];
  const partial: GlossaryEntry[] = [];
  for (const e of GLOSSARY) {
    const kos = e.ko.map((k) => k.replace(/\s+/g, ""));
    if (kos.some((k) => k === q || k.replace(/[(),]/g, "") === q)) exact.push(e);
    else if (q.length >= 2 && kos.some((k) => k.includes(q) || (k.length >= 2 && q.includes(k)))) partial.push(e);
  }
  return [...exact, ...partial].slice(0, limit);
}
